# Generated by Django 5.0.7 on 2024-07-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='raiting',
            new_name='rating',
        ),
    ]
